{% set name = "dom-toml" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dom_toml-{{ version }}.tar.gz
  sha256: 31c5874595c777f41cc191c34c66dbea215c8289a7b148b425fb7a10c3f4fbc8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - flit-core >=3.2,<4
    - pip
    - python {{ python_min }}
  run:
    - domdf-python-tools >=2.8.0
    - python >={{ python_min }}
    - tomli >=1.2.3

test:
  imports:
    - dom_toml
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/domdfcoding/dom_toml
  summary: Dom's tools for Tom's Obvious, Minimal Language.
  license: MIT
  license_file: LICENSE
  doc_url: https://dom_toml.readthedocs.io/en/latest

extra:
  recipe-maintainers:
    - domdfcoding
