{% set name = "dom-toml" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dom_toml-{{ version }}.tar.gz
  sha256: 2b8d4d1cdbca1839a4ef8582719ed9023410b7ae93094166d57a5bcbdfe2e305

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - flit-core >=3.2,<4
    - pip
    - python >=3.6
  run:
    - domdf-python-tools >=2.8.0
    - python >=3.6
    - toml >=0.10.2

test:
  imports:
    - dom_toml
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/domdfcoding/dom_toml
  summary: Dom's tools for Tom's Obvious, Minimal Language.
  license: MIT
  license_file: LICENSE
  doc_url: https://dom_toml.readthedocs.io/en/latest

extra:
  recipe-maintainers:
    - domdfcoding
