{% set name = "dom-toml" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dom_toml-{{ version }}.tar.gz
  sha256: a0bfc204ae32c72ed36e526dce56108a3b20741ac3c055207206ce3b2f302868

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - flit-core >=3.2,<4
    - pip
    - python >=3.6
  run:
    - domdf-python-tools >=2.8.0
    - python >=3.6
    - toml >=0.10.2

test:
  imports:
    - dom_toml
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/domdfcoding/dom_toml
  summary: Dom's tools for Tom's Obvious, Minimal Language.
  license: MIT
  license_file: LICENSE
  doc_url: https://dom_toml.readthedocs.io/en/latest

extra:
  recipe-maintainers:
    - domdfcoding
